# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  typo3:
    depends_on:
    - solr
    networks:
      typo3-solr:

  solr:
    image: ${SOLR_IMAGE}
    networks:
      typo3-solr:
    volumes:
    - solr:/opt/solr/server/solr/data
    restart: "${RESTART}"

networks:
  typo3-solr:

volumes:
  solr:
